service: line-kintai
frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

  memorySize: 256
  region: ap-northeast-1
  environment:
    LINE_CHANNEL_ID: Your Line Channel ID
    LINE_CHANNEL_SECRET: Your Line Channel Secret
    LINE_CHANNEL_TOKEN: Your Line Channel Token
    TEAMS_HOOK: Your Teams Hook Endpoint

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          path: /webhook
          method: post